[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "pne"
version = "0.1.0"
description = "A new generation agent core."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
dev-dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["pne"]
